name: Tự Động Cập Nhật Link MonPlayer

on:
  schedule:
    - cron: '*/10 * * * *' # Cứ 10 phút chạy 1 lần
  workflow_dispatch: # Cho phép bấm nút chạy bằng tay

jobs:
  update-link:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Ép hệ thống chạy Node.js mới nhất chống lỗi
    steps:
    - name: Kiểm tra code
      uses: actions/checkout@v4 # Nâng cấp từ v3 lên v4

    - name: Cài đặt Python
      uses: actions/setup-python@v5 # Nâng cấp từ v4 lên v5
      with:
        python-version: '3.11'

    - name: Cài đặt thư viện cần thiết
      run: pip install requests

    - name: Chạy script quét link
      run: python crawl.py

    - name: Đẩy file JSON mới lên GitHub
      run: |
        git config --global user.name "MonPlayer Bot"
        git config --global user.email "bot@monplayer.com"
        git add nguon.json
        git commit -m "Bot cập nhật link trận đấu mới" || exit 0
        git push
