name: Tự Động Cập Nhật Link MonPlayer

on:
  schedule:
    - cron: '*/10 * * * *' # Cứ 10 phút hệ thống tự động quét trận đấu 1 lần
  workflow_dispatch: # Cho phép bạn bấm nút chạy bằng tay nếu muốn

# Cấp quyền ghi file bắt buộc để robot có quyền đẩy file hoiquan.json lên kho của bạn
permissions:
  contents: write

jobs:
  update-link:
    runs-on: ubuntu-latest
    steps:
    - name: Kiểm tra code
      uses: actions/checkout@v4

    - name: Cài đặt Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cài đặt thư viện cần thiết
      run: pip install requests

    - name: Chạy script quét link
      run: python crawl.py

    - name: LỆNH QUAN TRỌNG - Đẩy file hoiquan.json lên GitHub chính
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add hoiquan.json
        git commit -m "Bot tự động cập nhật lịch thi đấu mới" || exit 0
        git push
